micronaut:
  banner:
    enabled: false

engine:
  window:
    width: 1280
    height: 720
    title: FFXI Client

ffxi:
  client:
    default-server-host: 127.0.0.1
    default-server-port: 35555
    keepalive-interval-ms: 5000
