<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>catalyst</groupId>
    <artifactId>ffxi-java</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>ffxi-engine</artifactId>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>catalyst</groupId>
      <artifactId>ffxi-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-inject</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-context</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-runtime</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.inject</groupId>
      <artifactId>jakarta.inject-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-glfw</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-opengl</artifactId>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl</artifactId>
      <classifier>natives-linux</classifier>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-glfw</artifactId>
      <classifier>natives-linux</classifier>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.lwjgl</groupId>
      <artifactId>lwjgl-opengl</artifactId>
      <classifier>natives-linux</classifier>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.github.spair</groupId>
      <artifactId>imgui-java-binding</artifactId>
      <version>${imgui.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.spair</groupId>
      <artifactId>imgui-java-lwjgl3</artifactId>
      <version>${imgui.version}</version>
    </dependency>
    <dependency>
      <groupId>io.github.spair</groupId>
      <artifactId>imgui-java-natives-linux</artifactId>
      <version>${imgui.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>
  </dependencies>

</project>
