micronaut:
  application:
    name: catalyst-login-service
  server:
    port: 8080

catalyst:
  tls:
    cert-path: /certs/tls.crt
    key-path: /certs/tls.key
    ca-path: /certs/ca.crt

endpoints:
  health:
    enabled: true
    sensitive: false
