micronaut:
  application:
    name: catalyst-gateway
  server:
    port: 8080

catalyst:
  gateway:
    port: 35555
    default-world-host: localhost
    default-world-port: 35002
    backends:
      LOGIN:
        policy: UNAUTHENTICATED
        host: localhost
        port: 35000
      LOBBY:
        policy: AUTHENTICATED
        host: localhost
        port: 35001

endpoints:
  health:
    enabled: true
    sensitive: false
