apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - port: 35555
      targetPort: 35555
      protocol: UDP
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: gateway
          image: catalyst-catalyst-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 35555
              protocol: UDP
          env:
            - name: CATALYST_GATEWAY_LOGINHOST
              value: "login-service"
            - name: CATALYST_GATEWAY_LOGINPORT
              value: "35556"
            - name: CATALYST_GATEWAY_LOBBYHOST
              value: "lobby-service"
            - name: CATALYST_GATEWAY_LOBBYPORT
              value: "35556"
            - name: CATALYST_GATEWAY_WORLDHOST
              value: "world-service"
            - name: CATALYST_GATEWAY_WORLDPORT
              value: "35556"
