apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - port: 35555
      targetPort: 35555
      protocol: UDP
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: gateway
          image: catalyst-catalyst-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 35555
              protocol: UDP
          env:
            - name: CATALYST_GATEWAY_LOGIN_SERVICE_HOST
              value: "login-service"
            - name: CATALYST_GATEWAY_LOGIN_SERVICE_PORT
              value: "35556"
            - name: CATALYST_GATEWAY_LOBBY_SERVICE_HOST
              value: "lobby-service"
            - name: CATALYST_GATEWAY_LOBBY_SERVICE_PORT
              value: "35556"
            - name: CATALYST_GATEWAY_WORLD_SERVICE_HOST
              value: "world-service"
            - name: CATALYST_GATEWAY_WORLD_SERVICE_PORT
              value: "35556"
