<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>catalyst</groupId>
    <artifactId>catalyst-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>catalyst-server-common</artifactId>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>catalyst</groupId>
      <artifactId>catalyst-common-network</artifactId>
    </dependency>
    <!-- Micronaut & Jakarta -->
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-inject</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.inject</groupId>
      <artifactId>jakarta.inject-api</artifactId>
    </dependency>
    <!-- Lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
    <!-- Logging -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty.incubator</groupId>
      <artifactId>netty-incubator-codec-classes-quic</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty.incubator</groupId>
      <artifactId>netty-incubator-codec-native-quic</artifactId>
      <classifier>linux-x86_64</classifier>
      <scope>runtime</scope>
    </dependency>
  </dependencies>


</project>
