micronaut:
  application:
    name: catalyst-lobby-service

catalyst:
  server:
    port: 35556
    session-timeout-seconds: 30
    auth-ticket-timeout-seconds: 300
    keepalive-interval-ms: 5000

datasources:
  default:
    url: ${CATALYST_DB_URL}
    username: ${CATALYST_DB_USERNAME}
    password: ${CATALYST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
