package catalyst.server.common.network;

/**
 * Represents the evolving state of a client's connection at the Gateway.
 */
public record ClientSession(
  long gatewaySessionId, // ALWAYS present. A unique ID generated by the Gateway when the QUIC stream opens.
  Long accountId,        // Null until the Login Service authenticates the user.
  Long characterId       // Null until the user successfully selects a character to play.
) {
  public boolean isAuthenticated() {
    return accountId != null;
  }

  public boolean isInWorld() {
    return characterId != null;
  }
}